### ISSUE TITLE
CAER-S dataset process

### ISSUE THREAD

**Issue by 0714lxy0714** [iiTzFrankie/DCJT#1]
作者你好，最近在阅读你的这篇文章Joint Training on Multiple Datasets with Inconsistent Labeling Criteria for Facial Expression Recognition，文章中提及CAER-S数据集经过处理。官方发布的数据集没有经过对齐处理，能方便分享一下CAER-S数据集的处理方法吗，这是我的邮箱1835190258@qq.com，非常感谢！ @iiTzFrankie

**Comment by Bennyggcc** [comment]
你好，我也想要文中几个数据集的处理方法，可以提供一下吗？这是我的邮箱xb_chen2022@163.com，谢谢。

**Comment by as43647** [comment]
你好，請問可以提供我數據集的處理方法嗎? 這是我的email: as43647@gmail.com，謝謝。
